### ISSUE TITLE
Provide options to set network timeout and delay

### ISSUE THREAD

**Issue by chad-earthscope** [iris-edu/slink2dali#1]
From Mark Chadwick:

> We’ve been doing some work with our main internet provider as they have been making firewall and routing changes between our datacentres recently. There’s another major one coming up soon, so we thought we might address an issue we have with slink2dali. Namely when the firewall/route change happens the slink2dali tool will hang for the prescribed 300 seconds before realising the other end has gone away and does a reconnect (with livens up the firewall packet matching etc., and it all starts to work happily).
 
> At the same time there have been some suggestions to change the netdly and netto parameters (mainly for connections within the datacentres rather than for connections out into the field), so I’ve had a quick go at adding them to the source of slink2dali-0.7.  I couldn’t find an associated IRIS git repo so a gist of the patch may be better than me sending patch files via email (which I know our spam filters don’t like).
 
> It’s a pretty simple change but just in case you or other users may benefit here’s the link.
 
https://gist.github.com/ozym/e6ba61fb43c738571d282ccb953e0edf
 
> I’ve changed the version number, but that’s only so we can track the version once it’s deployed.

**Comment by crotwell** [comment]
I'm using slink2dali to pull data from stations with digitizers that support seedlink (Obsidian) and the 300 second timeout seems too large for this use. In many cases a manual restart will reconnect well before the timeout hits. So configuring it would be useful. It would also be useful if the configuration was file based instead of command line args.

**Comment by chad-earthscope** [comment]
>  It would also be useful if the configuration was file based instead of command line args.

Can you describe in which cases it would be useful as opposed to command line?

**Comment by crotwell** [comment]
I use slink2dali to retrieve data from a station that has a seedlink enabled Obsidian. It is started from systemd at boot time, but that means that even though the command itself is run as a normal user, the startup file is owned by root and in /etc/systemd/system, which means edit requires sudo. But if slink2dali could accept a single arg that was a config file, then that config file could live with all the rest of my config files in a directory owned by the user. Ringserver, for example, uses a single conf file and I find that style much easier to keep track of and update.
